services:
  redis:
    image: 'redis:8.0-M02'
    ports:
      - '6379:6379'
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
#  ollama:
#    image: 'ollama/ollama:latest'
#    ports:
#      - '11434:11434'